# Generic start request message.  In this context, this is used
# to request a palm calibration cycle or movement.  Returns true
# if able to begin process.  This will likely expand to include
# some generic mode variables.

# There are two bits of thinking here: 

# 1. It is easier to guarantee system reliability if no event
# blocks for very long, so it is better to offer a service that
# begins an extended process rather than one which waits the
# entire time to return a value.  However, the calling process
# needs to monitor the progress output of the extended process
# and detect timeouts.

# 2. ROS and C++ encourage a plethora of special-purpose types
# which clutter the code with slightly divergent definitions.
# The idea here is that it is better to define some simpler types
# and re-use them, letting the context of use define their
# meaning.

---
int32 failure   # Set to 0 (success) or a numeric error code.
string msg      # Error description