#!/bin/sh

stty sane

ssh -t 192.168.1.7 "stty sane; roslaunch launch display.launch; stty sane"

stty sane

echo "********************************************"
echo "Connection to display computer closed"
echo "********************************************"
