(cl:in-package logger_comm-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          LOGTIMESTAMP-VAL
          LOGTIMESTAMP
          ID-VAL
          ID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          Q0-VAL
          Q0
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          J4-VAL
          J4
          J5-VAL
          J5
          J6-VAL
          J6
          FX-VAL
          FX
          FY-VAL
          FY
          FZ-VAL
          FZ
          TX-VAL
          TX
          TY-VAL
          TY
          TZ-VAL
          TZ
          ENCMOTOR-VAL
          ENCMOTOR
          ENCFINGER-VAL
          ENCFINGER
          ANGLEMOTOR-VAL
          ANGLEMOTOR
          ANGLE-VAL
          ANGLE
          RAWFORCES-VAL
          RAWFORCES
          FORCES-VAL
          FORCES
))