(cl:in-package robot_comm-srv)
(cl:export '(J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          J4-VAL
          J4
          J5-VAL
          J5
          J6-VAL
          J6
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          Q0-VAL
          Q0
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          RET-VAL
          RET
          MSG-VAL
          MSG
))