(cl:in-package robot_comm-srv)
(cl:export '(TCP-VAL
          TCP
          ORI-VAL
          ORI
          ZONE-VAL
          ZONE
          VACUUM-VAL
          VACUUM
          WORKX-VAL
          WORKX
          WORKY-VAL
          WORKY
          WORKZ-VAL
          WORKZ
          WORKQ0-VAL
          WORKQ0
          WORKQX-VAL
          WORKQX
          WORKQY-VAL
          WORKQY
          WORKQZ-VAL
          WORKQZ
          TOOLX-VAL
          TOOLX
          TOOLY-VAL
          TOOLY
          TOOLZ-VAL
          TOOLZ
          TOOLQ0-VAL
          TOOLQ0
          TOOLQX-VAL
          TOOLQX
          TOOLQY-VAL
          TOOLQY
          TOOLQZ-VAL
          TOOLQZ
          RET-VAL
          RET
          MSG-VAL
          MSG
))