/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/robot/ROS/robot_comm/srv/robot_SetTrackDist.srv */
#ifndef ROBOT_COMM_SERVICE_ROBOT_SETTRACKDIST_H
#define ROBOT_COMM_SERVICE_ROBOT_SETTRACKDIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comm
{
template <class ContainerAllocator>
struct robot_SetTrackDistRequest_ {
  typedef robot_SetTrackDistRequest_<ContainerAllocator> Type;

  robot_SetTrackDistRequest_()
  : pos_dist(0.0)
  , ang_dist(0.0)
  {
  }

  robot_SetTrackDistRequest_(const ContainerAllocator& _alloc)
  : pos_dist(0.0)
  , ang_dist(0.0)
  {
  }

  typedef double _pos_dist_type;
  double pos_dist;

  typedef double _ang_dist_type;
  double ang_dist;


  typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetTrackDistRequest
typedef  ::robot_comm::robot_SetTrackDistRequest_<std::allocator<void> > robot_SetTrackDistRequest;

typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistRequest> robot_SetTrackDistRequestPtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistRequest const> robot_SetTrackDistRequestConstPtr;



template <class ContainerAllocator>
struct robot_SetTrackDistResponse_ {
  typedef robot_SetTrackDistResponse_<ContainerAllocator> Type;

  robot_SetTrackDistResponse_()
  : ret(0)
  , msg()
  {
  }

  robot_SetTrackDistResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetTrackDistResponse
typedef  ::robot_comm::robot_SetTrackDistResponse_<std::allocator<void> > robot_SetTrackDistResponse;

typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistResponse> robot_SetTrackDistResponsePtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetTrackDistResponse const> robot_SetTrackDistResponseConstPtr;


struct robot_SetTrackDist
{

typedef robot_SetTrackDistRequest Request;
typedef robot_SetTrackDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct robot_SetTrackDist
} // namespace robot_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "83ebed908297f9c3e07ef540f9857ab1";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x83ebed908297f9c3ULL;
  static const uint64_t static_value2 = 0xe07ef540f9857ab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetTrackDistRequest";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
float64 pos_dist\n\
float64 ang_dist\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetTrackDistResponse";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pos_dist);
    stream.next(m.ang_dist);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetTrackDistRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetTrackDistResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comm::robot_SetTrackDist> {
  static const char* value() 
  {
    return "eb267eb8369d9c3a686d934285ba7a11";
  }

  static const char* value(const robot_comm::robot_SetTrackDist&) { return value(); } 
};

template<>
struct DataType<robot_comm::robot_SetTrackDist> {
  static const char* value() 
  {
    return "robot_comm/robot_SetTrackDist";
  }

  static const char* value(const robot_comm::robot_SetTrackDist&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb267eb8369d9c3a686d934285ba7a11";
  }

  static const char* value(const robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetTrackDist";
  }

  static const char* value(const robot_comm::robot_SetTrackDistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb267eb8369d9c3a686d934285ba7a11";
  }

  static const char* value(const robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetTrackDist";
  }

  static const char* value(const robot_comm::robot_SetTrackDistResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMM_SERVICE_ROBOT_SETTRACKDIST_H

