/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/robot/ROS/robot_comm/srv/robot_Ping.srv */
#ifndef ROBOT_COMM_SERVICE_ROBOT_PING_H
#define ROBOT_COMM_SERVICE_ROBOT_PING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comm
{
template <class ContainerAllocator>
struct robot_PingRequest_ {
  typedef robot_PingRequest_<ContainerAllocator> Type;

  robot_PingRequest_()
  {
  }

  robot_PingRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::robot_comm::robot_PingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_PingRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_PingRequest
typedef  ::robot_comm::robot_PingRequest_<std::allocator<void> > robot_PingRequest;

typedef boost::shared_ptr< ::robot_comm::robot_PingRequest> robot_PingRequestPtr;
typedef boost::shared_ptr< ::robot_comm::robot_PingRequest const> robot_PingRequestConstPtr;



template <class ContainerAllocator>
struct robot_PingResponse_ {
  typedef robot_PingResponse_<ContainerAllocator> Type;

  robot_PingResponse_()
  : ret(0)
  , msg()
  {
  }

  robot_PingResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::robot_comm::robot_PingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_PingResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_PingResponse
typedef  ::robot_comm::robot_PingResponse_<std::allocator<void> > robot_PingResponse;

typedef boost::shared_ptr< ::robot_comm::robot_PingResponse> robot_PingResponsePtr;
typedef boost::shared_ptr< ::robot_comm::robot_PingResponse const> robot_PingResponseConstPtr;


struct robot_Ping
{

typedef robot_PingRequest Request;
typedef robot_PingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct robot_Ping
} // namespace robot_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_PingRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_PingRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_PingRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::robot_comm::robot_PingRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_PingRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_PingRequest";
  }

  static const char* value(const  ::robot_comm::robot_PingRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_PingRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_PingRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comm::robot_PingRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_PingResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_PingResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_PingResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::robot_comm::robot_PingResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_PingResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_PingResponse";
  }

  static const char* value(const  ::robot_comm::robot_PingResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_PingResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_PingResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_PingRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_PingRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_PingResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_PingResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comm::robot_Ping> {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const robot_comm::robot_Ping&) { return value(); } 
};

template<>
struct DataType<robot_comm::robot_Ping> {
  static const char* value() 
  {
    return "robot_comm/robot_Ping";
  }

  static const char* value(const robot_comm::robot_Ping&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_PingRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const robot_comm::robot_PingRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_PingRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_Ping";
  }

  static const char* value(const robot_comm::robot_PingRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_PingResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const robot_comm::robot_PingResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_PingResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_Ping";
  }

  static const char* value(const robot_comm::robot_PingResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMM_SERVICE_ROBOT_PING_H

