/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/robot/ROS/robot_comm/srv/robot_SetVacuum.srv */
#ifndef ROBOT_COMM_SERVICE_ROBOT_SETVACUUM_H
#define ROBOT_COMM_SERVICE_ROBOT_SETVACUUM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comm
{
template <class ContainerAllocator>
struct robot_SetVacuumRequest_ {
  typedef robot_SetVacuumRequest_<ContainerAllocator> Type;

  robot_SetVacuumRequest_()
  : vacuum(0)
  {
  }

  robot_SetVacuumRequest_(const ContainerAllocator& _alloc)
  : vacuum(0)
  {
  }

  typedef int64_t _vacuum_type;
  int64_t vacuum;


  typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetVacuumRequest
typedef  ::robot_comm::robot_SetVacuumRequest_<std::allocator<void> > robot_SetVacuumRequest;

typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumRequest> robot_SetVacuumRequestPtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumRequest const> robot_SetVacuumRequestConstPtr;



template <class ContainerAllocator>
struct robot_SetVacuumResponse_ {
  typedef robot_SetVacuumResponse_<ContainerAllocator> Type;

  robot_SetVacuumResponse_()
  : ret(0)
  , msg()
  {
  }

  robot_SetVacuumResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetVacuumResponse
typedef  ::robot_comm::robot_SetVacuumResponse_<std::allocator<void> > robot_SetVacuumResponse;

typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumResponse> robot_SetVacuumResponsePtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetVacuumResponse const> robot_SetVacuumResponseConstPtr;


struct robot_SetVacuum
{

typedef robot_SetVacuumRequest Request;
typedef robot_SetVacuumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct robot_SetVacuum
} // namespace robot_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6ee7741d1da0c9620d77add3d4997c2d";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6ee7741d1da0c962ULL;
  static const uint64_t static_value2 = 0x0d77add3d4997c2dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetVacuumRequest";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
int64 vacuum\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetVacuumResponse";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetVacuumRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.vacuum);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetVacuumRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetVacuumResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetVacuumResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comm::robot_SetVacuum> {
  static const char* value() 
  {
    return "bc2b2a4e5d5d788edc958a62cf84dc1f";
  }

  static const char* value(const robot_comm::robot_SetVacuum&) { return value(); } 
};

template<>
struct DataType<robot_comm::robot_SetVacuum> {
  static const char* value() 
  {
    return "robot_comm/robot_SetVacuum";
  }

  static const char* value(const robot_comm::robot_SetVacuum&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bc2b2a4e5d5d788edc958a62cf84dc1f";
  }

  static const char* value(const robot_comm::robot_SetVacuumRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetVacuumRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetVacuum";
  }

  static const char* value(const robot_comm::robot_SetVacuumRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bc2b2a4e5d5d788edc958a62cf84dc1f";
  }

  static const char* value(const robot_comm::robot_SetVacuumResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetVacuumResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetVacuum";
  }

  static const char* value(const robot_comm::robot_SetVacuumResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMM_SERVICE_ROBOT_SETVACUUM_H

