/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/robot/ROS/robot_comm/srv/robot_SetSpeed.srv */
#ifndef ROBOT_COMM_SERVICE_ROBOT_SETSPEED_H
#define ROBOT_COMM_SERVICE_ROBOT_SETSPEED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comm
{
template <class ContainerAllocator>
struct robot_SetSpeedRequest_ {
  typedef robot_SetSpeedRequest_<ContainerAllocator> Type;

  robot_SetSpeedRequest_()
  : tcp(0.0)
  , ori(0.0)
  {
  }

  robot_SetSpeedRequest_(const ContainerAllocator& _alloc)
  : tcp(0.0)
  , ori(0.0)
  {
  }

  typedef double _tcp_type;
  double tcp;

  typedef double _ori_type;
  double ori;


  typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetSpeedRequest
typedef  ::robot_comm::robot_SetSpeedRequest_<std::allocator<void> > robot_SetSpeedRequest;

typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedRequest> robot_SetSpeedRequestPtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedRequest const> robot_SetSpeedRequestConstPtr;



template <class ContainerAllocator>
struct robot_SetSpeedResponse_ {
  typedef robot_SetSpeedResponse_<ContainerAllocator> Type;

  robot_SetSpeedResponse_()
  : ret(0)
  , msg()
  {
  }

  robot_SetSpeedResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_SetSpeedResponse
typedef  ::robot_comm::robot_SetSpeedResponse_<std::allocator<void> > robot_SetSpeedResponse;

typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedResponse> robot_SetSpeedResponsePtr;
typedef boost::shared_ptr< ::robot_comm::robot_SetSpeedResponse const> robot_SetSpeedResponseConstPtr;


struct robot_SetSpeed
{

typedef robot_SetSpeedRequest Request;
typedef robot_SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct robot_SetSpeed
} // namespace robot_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9f0ff1193cfb3499a7608d4091f40f93";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9f0ff1193cfb3499ULL;
  static const uint64_t static_value2 = 0xa7608d4091f40f93ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetSpeedRequest";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
float64 tcp\n\
float64 ori\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetSpeedResponse";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.tcp);
    stream.next(m.ori);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetSpeedRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_SetSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_SetSpeedResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comm::robot_SetSpeed> {
  static const char* value() 
  {
    return "333d89e728aabc050c209d2cd3cd6dc2";
  }

  static const char* value(const robot_comm::robot_SetSpeed&) { return value(); } 
};

template<>
struct DataType<robot_comm::robot_SetSpeed> {
  static const char* value() 
  {
    return "robot_comm/robot_SetSpeed";
  }

  static const char* value(const robot_comm::robot_SetSpeed&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "333d89e728aabc050c209d2cd3cd6dc2";
  }

  static const char* value(const robot_comm::robot_SetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetSpeed";
  }

  static const char* value(const robot_comm::robot_SetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "333d89e728aabc050c209d2cd3cd6dc2";
  }

  static const char* value(const robot_comm::robot_SetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_SetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_SetSpeed";
  }

  static const char* value(const robot_comm::robot_SetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMM_SERVICE_ROBOT_SETSPEED_H

