/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/robot/ROS/robot_comm/srv/robot_GetJoints.srv */
#ifndef ROBOT_COMM_SERVICE_ROBOT_GETJOINTS_H
#define ROBOT_COMM_SERVICE_ROBOT_GETJOINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comm
{
template <class ContainerAllocator>
struct robot_GetJointsRequest_ {
  typedef robot_GetJointsRequest_<ContainerAllocator> Type;

  robot_GetJointsRequest_()
  {
  }

  robot_GetJointsRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_GetJointsRequest
typedef  ::robot_comm::robot_GetJointsRequest_<std::allocator<void> > robot_GetJointsRequest;

typedef boost::shared_ptr< ::robot_comm::robot_GetJointsRequest> robot_GetJointsRequestPtr;
typedef boost::shared_ptr< ::robot_comm::robot_GetJointsRequest const> robot_GetJointsRequestConstPtr;



template <class ContainerAllocator>
struct robot_GetJointsResponse_ {
  typedef robot_GetJointsResponse_<ContainerAllocator> Type;

  robot_GetJointsResponse_()
  : j1(0.0)
  , j2(0.0)
  , j3(0.0)
  , j4(0.0)
  , j5(0.0)
  , j6(0.0)
  , ret(0)
  , msg()
  {
  }

  robot_GetJointsResponse_(const ContainerAllocator& _alloc)
  : j1(0.0)
  , j2(0.0)
  , j3(0.0)
  , j4(0.0)
  , j5(0.0)
  , j6(0.0)
  , ret(0)
  , msg(_alloc)
  {
  }

  typedef double _j1_type;
  double j1;

  typedef double _j2_type;
  double j2;

  typedef double _j3_type;
  double j3;

  typedef double _j4_type;
  double j4;

  typedef double _j5_type;
  double j5;

  typedef double _j6_type;
  double j6;

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct robot_GetJointsResponse
typedef  ::robot_comm::robot_GetJointsResponse_<std::allocator<void> > robot_GetJointsResponse;

typedef boost::shared_ptr< ::robot_comm::robot_GetJointsResponse> robot_GetJointsResponsePtr;
typedef boost::shared_ptr< ::robot_comm::robot_GetJointsResponse const> robot_GetJointsResponseConstPtr;


struct robot_GetJoints
{

typedef robot_GetJointsRequest Request;
typedef robot_GetJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct robot_GetJoints
} // namespace robot_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_GetJointsRequest";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "927b82d08077d046362055bd87d33b65";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x927b82d08077d046ULL;
  static const uint64_t static_value2 = 0x362055bd87d33b65ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_GetJointsResponse";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 j1\n\
float64 j2\n\
float64 j3\n\
float64 j4\n\
float64 j5\n\
float64 j6\n\
int64 ret\n\
string msg\n\
\n\
";
  }

  static const char* value(const  ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_GetJointsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_GetJointsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comm::robot_GetJointsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.j1);
    stream.next(m.j2);
    stream.next(m.j3);
    stream.next(m.j4);
    stream.next(m.j5);
    stream.next(m.j6);
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct robot_GetJointsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comm::robot_GetJoints> {
  static const char* value() 
  {
    return "927b82d08077d046362055bd87d33b65";
  }

  static const char* value(const robot_comm::robot_GetJoints&) { return value(); } 
};

template<>
struct DataType<robot_comm::robot_GetJoints> {
  static const char* value() 
  {
    return "robot_comm/robot_GetJoints";
  }

  static const char* value(const robot_comm::robot_GetJoints&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_GetJointsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "927b82d08077d046362055bd87d33b65";
  }

  static const char* value(const robot_comm::robot_GetJointsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_GetJointsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_GetJoints";
  }

  static const char* value(const robot_comm::robot_GetJointsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comm::robot_GetJointsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "927b82d08077d046362055bd87d33b65";
  }

  static const char* value(const robot_comm::robot_GetJointsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comm::robot_GetJointsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comm/robot_GetJoints";
  }

  static const char* value(const robot_comm::robot_GetJointsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMM_SERVICE_ROBOT_GETJOINTS_H

