/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/logger/ROS/logger_comm/srv/logger_Copy.srv */
#ifndef LOGGER_COMM_SERVICE_LOGGER_COPY_H
#define LOGGER_COMM_SERVICE_LOGGER_COPY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace logger_comm
{
template <class ContainerAllocator>
struct logger_CopyRequest_ {
  typedef logger_CopyRequest_<ContainerAllocator> Type;

  logger_CopyRequest_()
  : filename()
  , folder()
  {
  }

  logger_CopyRequest_(const ContainerAllocator& _alloc)
  : filename(_alloc)
  , folder(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  filename;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _folder_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  folder;


  typedef boost::shared_ptr< ::logger_comm::logger_CopyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger_comm::logger_CopyRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct logger_CopyRequest
typedef  ::logger_comm::logger_CopyRequest_<std::allocator<void> > logger_CopyRequest;

typedef boost::shared_ptr< ::logger_comm::logger_CopyRequest> logger_CopyRequestPtr;
typedef boost::shared_ptr< ::logger_comm::logger_CopyRequest const> logger_CopyRequestConstPtr;



template <class ContainerAllocator>
struct logger_CopyResponse_ {
  typedef logger_CopyResponse_<ContainerAllocator> Type;

  logger_CopyResponse_()
  : ret(0)
  , msg()
  {
  }

  logger_CopyResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::logger_comm::logger_CopyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger_comm::logger_CopyResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct logger_CopyResponse
typedef  ::logger_comm::logger_CopyResponse_<std::allocator<void> > logger_CopyResponse;

typedef boost::shared_ptr< ::logger_comm::logger_CopyResponse> logger_CopyResponsePtr;
typedef boost::shared_ptr< ::logger_comm::logger_CopyResponse const> logger_CopyResponseConstPtr;


struct logger_Copy
{

typedef logger_CopyRequest Request;
typedef logger_CopyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct logger_Copy
} // namespace logger_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::logger_comm::logger_CopyRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::logger_comm::logger_CopyRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::logger_comm::logger_CopyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "300ad27a9d0da7f6ec1874faf792434b";
  }

  static const char* value(const  ::logger_comm::logger_CopyRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x300ad27a9d0da7f6ULL;
  static const uint64_t static_value2 = 0xec1874faf792434bULL;
};

template<class ContainerAllocator>
struct DataType< ::logger_comm::logger_CopyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "logger_comm/logger_CopyRequest";
  }

  static const char* value(const  ::logger_comm::logger_CopyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::logger_comm::logger_CopyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string filename\n\
string folder\n\
\n\
";
  }

  static const char* value(const  ::logger_comm::logger_CopyRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::logger_comm::logger_CopyResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::logger_comm::logger_CopyResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::logger_comm::logger_CopyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::logger_comm::logger_CopyResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::logger_comm::logger_CopyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "logger_comm/logger_CopyResponse";
  }

  static const char* value(const  ::logger_comm::logger_CopyResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::logger_comm::logger_CopyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::logger_comm::logger_CopyResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::logger_comm::logger_CopyRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.filename);
    stream.next(m.folder);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct logger_CopyRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::logger_comm::logger_CopyResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct logger_CopyResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<logger_comm::logger_Copy> {
  static const char* value() 
  {
    return "3427d5531530b2330c888216f5d9175b";
  }

  static const char* value(const logger_comm::logger_Copy&) { return value(); } 
};

template<>
struct DataType<logger_comm::logger_Copy> {
  static const char* value() 
  {
    return "logger_comm/logger_Copy";
  }

  static const char* value(const logger_comm::logger_Copy&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<logger_comm::logger_CopyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3427d5531530b2330c888216f5d9175b";
  }

  static const char* value(const logger_comm::logger_CopyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<logger_comm::logger_CopyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "logger_comm/logger_Copy";
  }

  static const char* value(const logger_comm::logger_CopyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<logger_comm::logger_CopyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3427d5531530b2330c888216f5d9175b";
  }

  static const char* value(const logger_comm::logger_CopyResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<logger_comm::logger_CopyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "logger_comm/logger_Copy";
  }

  static const char* value(const logger_comm::logger_CopyResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // LOGGER_COMM_SERVICE_LOGGER_COPY_H

