/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/hand/ROS/hand_comm/msg/hand_AnglesLog.msg */
#ifndef HAND_COMM_MESSAGE_HAND_ANGLESLOG_H
#define HAND_COMM_MESSAGE_HAND_ANGLESLOG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hand_comm
{
template <class ContainerAllocator>
struct hand_AnglesLog_ {
  typedef hand_AnglesLog_<ContainerAllocator> Type;

  hand_AnglesLog_()
  : timeStamp(0.0)
  , angleMotor(0.0)
  , angle()
  {
  }

  hand_AnglesLog_(const ContainerAllocator& _alloc)
  : timeStamp(0.0)
  , angleMotor(0.0)
  , angle(_alloc)
  {
  }

  typedef double _timeStamp_type;
  double timeStamp;

  typedef double _angleMotor_type;
  double angleMotor;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angle_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  angle;


  typedef boost::shared_ptr< ::hand_comm::hand_AnglesLog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_AnglesLog_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_AnglesLog
typedef  ::hand_comm::hand_AnglesLog_<std::allocator<void> > hand_AnglesLog;

typedef boost::shared_ptr< ::hand_comm::hand_AnglesLog> hand_AnglesLogPtr;
typedef boost::shared_ptr< ::hand_comm::hand_AnglesLog const> hand_AnglesLogConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hand_comm::hand_AnglesLog_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hand_comm::hand_AnglesLog_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hand_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_AnglesLog_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_AnglesLog_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_AnglesLog_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b85e73c680cf47f4b263c17a913f644a";
  }

  static const char* value(const  ::hand_comm::hand_AnglesLog_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb85e73c680cf47f4ULL;
  static const uint64_t static_value2 = 0xb263c17a913f644aULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_AnglesLog_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_AnglesLog";
  }

  static const char* value(const  ::hand_comm::hand_AnglesLog_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_AnglesLog_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 timeStamp      # ROS time-stamp\n\
float64 angleMotor     # Motor angle\n\
float64[] angle        # Finger angles\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_AnglesLog_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_AnglesLog_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timeStamp);
    stream.next(m.angleMotor);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_AnglesLog_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_comm::hand_AnglesLog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hand_comm::hand_AnglesLog_<ContainerAllocator> & v) 
  {
    s << indent << "timeStamp: ";
    Printer<double>::stream(s, indent + "  ", v.timeStamp);
    s << indent << "angleMotor: ";
    Printer<double>::stream(s, indent + "  ", v.angleMotor);
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // HAND_COMM_MESSAGE_HAND_ANGLESLOG_H

