#!/usr/bin/env python
import roslib; roslib.load_manifest('vision')
import sys
import rospy
import cv
import cv2
import numpy as np

from vision.msg import posmsg

from sensor_msgs.msg import Image

from cv_bridge import CvBridge, CvBridgeError




def main():
    
    
    vision.init()
    
#    cv.NamedWindow("Image window", 1) #start a window
    rospy.init_node('vision_node')     #init the node
    rospy.Subscriber("/camera/rgb/image_color", Image, vision.callback) #subscribe to the camera topic, and start the function callback
    

    
    #cv.WaitKey(1000)    
    rospy.spin() #keps the node running

   

if __name__ == '__main__':
    
    vision=vision()
    main()
