#!/bin/bash
# This shell script creates a new file that moves the robot and 
# loads the new calibration into a YAML file, that then the 
# container node reads from, so that the Kinect's Robot_Points
# uses an accurate transform.

# Save the old data file.

base=~/Documents/hands/code/nodes/calibration/old_data/
currentTime=$(date "+%F_%H.%M.%S")
tail=_data.txt

cp ~/Documents/hands/code/nodes/calibration/data.txt $base$currentTime$tail 

# First, run the calibration sequence.
rosrun calibration get_points_in_both_frames

# SCP into the main computer and put the output there.

cd ~/Documents/hands/code/nodes/calibration
scp data.txt 192.168.1.4:~/Documents/hands/code/nodes/calibration/data.txt
cd ~

# Keep the old params as another file.

base=~/Documents/hands/code/parameters/old_transform_params/
tail=_params.yaml

cp ~/Documents/hands/code/parameters/transform_params.yaml $base$currentTime$tail 

# Then, access that file, use Matlab to get the transform.
# Now, write the transform to a YAML file. 

rosrun calibration write_transform_to_file

# Load the parameters to the parameter server.
cd ~/Documents/hands/code/parameters 
rosparam load transform_params.yaml

# At this point, the container node will simply use those points 
# to transform the cloud.
exit 0
