/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/vision/ROS/objRec_comm/srv/objRec_SetBounds.srv */
#ifndef OBJREC_COMM_SERVICE_OBJREC_SETBOUNDS_H
#define OBJREC_COMM_SERVICE_OBJREC_SETBOUNDS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace objRec_comm
{
template <class ContainerAllocator>
struct objRec_SetBoundsRequest_ {
  typedef objRec_SetBoundsRequest_<ContainerAllocator> Type;

  objRec_SetBoundsRequest_()
  : widths()
  , trans()
  , quat()
  {
    widths.assign(0.0);
    trans.assign(0.0);
    quat.assign(0.0);
  }

  objRec_SetBoundsRequest_(const ContainerAllocator& _alloc)
  : widths()
  , trans()
  , quat()
  {
    widths.assign(0.0);
    trans.assign(0.0);
    quat.assign(0.0);
  }

  typedef boost::array<double, 3>  _widths_type;
  boost::array<double, 3>  widths;

  typedef boost::array<double, 3>  _trans_type;
  boost::array<double, 3>  trans;

  typedef boost::array<double, 4>  _quat_type;
  boost::array<double, 4>  quat;


  typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct objRec_SetBoundsRequest
typedef  ::objRec_comm::objRec_SetBoundsRequest_<std::allocator<void> > objRec_SetBoundsRequest;

typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsRequest> objRec_SetBoundsRequestPtr;
typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsRequest const> objRec_SetBoundsRequestConstPtr;



template <class ContainerAllocator>
struct objRec_SetBoundsResponse_ {
  typedef objRec_SetBoundsResponse_<ContainerAllocator> Type;

  objRec_SetBoundsResponse_()
  : ret(0)
  , msg()
  {
  }

  objRec_SetBoundsResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct objRec_SetBoundsResponse
typedef  ::objRec_comm::objRec_SetBoundsResponse_<std::allocator<void> > objRec_SetBoundsResponse;

typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsResponse> objRec_SetBoundsResponsePtr;
typedef boost::shared_ptr< ::objRec_comm::objRec_SetBoundsResponse const> objRec_SetBoundsResponseConstPtr;


struct objRec_SetBounds
{

typedef objRec_SetBoundsRequest Request;
typedef objRec_SetBoundsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct objRec_SetBounds
} // namespace objRec_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e7133ce87088588c58b1b9c3ea68dcff";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe7133ce87088588cULL;
  static const uint64_t static_value2 = 0x58b1b9c3ea68dcffULL;
};

template<class ContainerAllocator>
struct DataType< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objRec_comm/objRec_SetBoundsRequest";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
float64[3] widths\n\
\n\
float64[3] trans\n\
float64[4] quat\n\
\n\
\n\
";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objRec_comm/objRec_SetBoundsResponse";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int64 ret\n\
string msg\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.widths);
    stream.next(m.trans);
    stream.next(m.quat);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct objRec_SetBoundsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct objRec_SetBoundsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<objRec_comm::objRec_SetBounds> {
  static const char* value() 
  {
    return "10e95f96c4eb24ec7cd23fd9df5fae89";
  }

  static const char* value(const objRec_comm::objRec_SetBounds&) { return value(); } 
};

template<>
struct DataType<objRec_comm::objRec_SetBounds> {
  static const char* value() 
  {
    return "objRec_comm/objRec_SetBounds";
  }

  static const char* value(const objRec_comm::objRec_SetBounds&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "10e95f96c4eb24ec7cd23fd9df5fae89";
  }

  static const char* value(const objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objRec_comm/objRec_SetBounds";
  }

  static const char* value(const objRec_comm::objRec_SetBoundsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "10e95f96c4eb24ec7cd23fd9df5fae89";
  }

  static const char* value(const objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objRec_comm/objRec_SetBounds";
  }

  static const char* value(const objRec_comm::objRec_SetBoundsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OBJREC_COMM_SERVICE_OBJREC_SETBOUNDS_H

