/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/hand/ROS/hand_comm/srv/hand_SetEncoder.srv */
#ifndef HAND_COMM_SERVICE_HAND_SETENCODER_H
#define HAND_COMM_SERVICE_HAND_SETENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hand_comm
{
template <class ContainerAllocator>
struct hand_SetEncoderRequest_ {
  typedef hand_SetEncoderRequest_<ContainerAllocator> Type;

  hand_SetEncoderRequest_()
  : enc(0)
  {
  }

  hand_SetEncoderRequest_(const ContainerAllocator& _alloc)
  : enc(0)
  {
  }

  typedef int64_t _enc_type;
  int64_t enc;


  typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_SetEncoderRequest
typedef  ::hand_comm::hand_SetEncoderRequest_<std::allocator<void> > hand_SetEncoderRequest;

typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderRequest> hand_SetEncoderRequestPtr;
typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderRequest const> hand_SetEncoderRequestConstPtr;



template <class ContainerAllocator>
struct hand_SetEncoderResponse_ {
  typedef hand_SetEncoderResponse_<ContainerAllocator> Type;

  hand_SetEncoderResponse_()
  : ret(0)
  , msg()
  {
  }

  hand_SetEncoderResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_SetEncoderResponse
typedef  ::hand_comm::hand_SetEncoderResponse_<std::allocator<void> > hand_SetEncoderResponse;

typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderResponse> hand_SetEncoderResponsePtr;
typedef boost::shared_ptr< ::hand_comm::hand_SetEncoderResponse const> hand_SetEncoderResponseConstPtr;


struct hand_SetEncoder
{

typedef hand_SetEncoderRequest Request;
typedef hand_SetEncoderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct hand_SetEncoder
} // namespace hand_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f17c4e7ccff9c107a904bb75cbb99c36";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf17c4e7ccff9c107ULL;
  static const uint64_t static_value2 = 0xa904bb75cbb99c36ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_SetEncoderRequest";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int64 enc\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e32786be6359fbbULL;
  static const uint64_t static_value2 = 0xb6259aee4f579d10ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_SetEncoderResponse";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 ret\n\
string msg\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_SetEncoderRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.enc);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_SetEncoderRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_SetEncoderResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_SetEncoderResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hand_comm::hand_SetEncoder> {
  static const char* value() 
  {
    return "bae9129085a26b4bc21b9405f82428dc";
  }

  static const char* value(const hand_comm::hand_SetEncoder&) { return value(); } 
};

template<>
struct DataType<hand_comm::hand_SetEncoder> {
  static const char* value() 
  {
    return "hand_comm/hand_SetEncoder";
  }

  static const char* value(const hand_comm::hand_SetEncoder&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bae9129085a26b4bc21b9405f82428dc";
  }

  static const char* value(const hand_comm::hand_SetEncoderRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_SetEncoderRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_SetEncoder";
  }

  static const char* value(const hand_comm::hand_SetEncoderRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bae9129085a26b4bc21b9405f82428dc";
  }

  static const char* value(const hand_comm::hand_SetEncoderResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_SetEncoderResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_SetEncoder";
  }

  static const char* value(const hand_comm::hand_SetEncoderResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HAND_COMM_SERVICE_HAND_SETENCODER_H

