/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/hand/ROS/hand_comm/srv/hand_GetForces.srv */
#ifndef HAND_COMM_SERVICE_HAND_GETFORCES_H
#define HAND_COMM_SERVICE_HAND_GETFORCES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hand_comm
{
template <class ContainerAllocator>
struct hand_GetForcesRequest_ {
  typedef hand_GetForcesRequest_<ContainerAllocator> Type;

  hand_GetForcesRequest_()
  {
  }

  hand_GetForcesRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetForcesRequest
typedef  ::hand_comm::hand_GetForcesRequest_<std::allocator<void> > hand_GetForcesRequest;

typedef boost::shared_ptr< ::hand_comm::hand_GetForcesRequest> hand_GetForcesRequestPtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetForcesRequest const> hand_GetForcesRequestConstPtr;



template <class ContainerAllocator>
struct hand_GetForcesResponse_ {
  typedef hand_GetForcesResponse_<ContainerAllocator> Type;

  hand_GetForcesResponse_()
  : forces()
  , ret(0)
  , msg()
  {
  }

  hand_GetForcesResponse_(const ContainerAllocator& _alloc)
  : forces(_alloc)
  , ret(0)
  , msg(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _forces_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  forces;

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetForcesResponse
typedef  ::hand_comm::hand_GetForcesResponse_<std::allocator<void> > hand_GetForcesResponse;

typedef boost::shared_ptr< ::hand_comm::hand_GetForcesResponse> hand_GetForcesResponsePtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetForcesResponse const> hand_GetForcesResponseConstPtr;


struct hand_GetForces
{

typedef hand_GetForcesRequest Request;
typedef hand_GetForcesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct hand_GetForces
} // namespace hand_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetForcesRequest";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5db9f3d8c42e861d773a8623b84074bd";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5db9f3d8c42e861dULL;
  static const uint64_t static_value2 = 0x773a8623b84074bdULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetForcesResponse";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] forces\n\
int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetForcesRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetForcesRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetForcesResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.forces);
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetForcesResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hand_comm::hand_GetForces> {
  static const char* value() 
  {
    return "5db9f3d8c42e861d773a8623b84074bd";
  }

  static const char* value(const hand_comm::hand_GetForces&) { return value(); } 
};

template<>
struct DataType<hand_comm::hand_GetForces> {
  static const char* value() 
  {
    return "hand_comm/hand_GetForces";
  }

  static const char* value(const hand_comm::hand_GetForces&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5db9f3d8c42e861d773a8623b84074bd";
  }

  static const char* value(const hand_comm::hand_GetForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetForces";
  }

  static const char* value(const hand_comm::hand_GetForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5db9f3d8c42e861d773a8623b84074bd";
  }

  static const char* value(const hand_comm::hand_GetForcesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetForces";
  }

  static const char* value(const hand_comm::hand_GetForcesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HAND_COMM_SERVICE_HAND_GETFORCES_H

