/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/hand/ROS/hand_comm/srv/hand_GetEncoders.srv */
#ifndef HAND_COMM_SERVICE_HAND_GETENCODERS_H
#define HAND_COMM_SERVICE_HAND_GETENCODERS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hand_comm
{
template <class ContainerAllocator>
struct hand_GetEncodersRequest_ {
  typedef hand_GetEncodersRequest_<ContainerAllocator> Type;

  hand_GetEncodersRequest_()
  {
  }

  hand_GetEncodersRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetEncodersRequest
typedef  ::hand_comm::hand_GetEncodersRequest_<std::allocator<void> > hand_GetEncodersRequest;

typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersRequest> hand_GetEncodersRequestPtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersRequest const> hand_GetEncodersRequestConstPtr;



template <class ContainerAllocator>
struct hand_GetEncodersResponse_ {
  typedef hand_GetEncodersResponse_<ContainerAllocator> Type;

  hand_GetEncodersResponse_()
  : encMotor(0)
  , encFinger()
  , ret(0)
  , msg()
  {
  }

  hand_GetEncodersResponse_(const ContainerAllocator& _alloc)
  : encMotor(0)
  , encFinger(_alloc)
  , ret(0)
  , msg(_alloc)
  {
  }

  typedef int64_t _encMotor_type;
  int64_t encMotor;

  typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _encFinger_type;
  std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  encFinger;

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetEncodersResponse
typedef  ::hand_comm::hand_GetEncodersResponse_<std::allocator<void> > hand_GetEncodersResponse;

typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersResponse> hand_GetEncodersResponsePtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetEncodersResponse const> hand_GetEncodersResponseConstPtr;


struct hand_GetEncoders
{

typedef hand_GetEncodersRequest Request;
typedef hand_GetEncodersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct hand_GetEncoders
} // namespace hand_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetEncodersRequest";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d5ab16d52ee0363bea7657bda39d668";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7d5ab16d52ee0363ULL;
  static const uint64_t static_value2 = 0xbea7657bda39d668ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetEncodersResponse";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 encMotor\n\
int64[] encFinger\n\
int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetEncodersRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetEncodersRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetEncodersResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.encMotor);
    stream.next(m.encFinger);
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetEncodersResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hand_comm::hand_GetEncoders> {
  static const char* value() 
  {
    return "7d5ab16d52ee0363bea7657bda39d668";
  }

  static const char* value(const hand_comm::hand_GetEncoders&) { return value(); } 
};

template<>
struct DataType<hand_comm::hand_GetEncoders> {
  static const char* value() 
  {
    return "hand_comm/hand_GetEncoders";
  }

  static const char* value(const hand_comm::hand_GetEncoders&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d5ab16d52ee0363bea7657bda39d668";
  }

  static const char* value(const hand_comm::hand_GetEncodersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetEncodersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetEncoders";
  }

  static const char* value(const hand_comm::hand_GetEncodersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d5ab16d52ee0363bea7657bda39d668";
  }

  static const char* value(const hand_comm::hand_GetEncodersResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetEncodersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetEncoders";
  }

  static const char* value(const hand_comm::hand_GetEncodersResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HAND_COMM_SERVICE_HAND_GETENCODERS_H

