/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/hand/ROS/hand_comm/srv/hand_GetRawForces.srv */
#ifndef HAND_COMM_SERVICE_HAND_GETRAWFORCES_H
#define HAND_COMM_SERVICE_HAND_GETRAWFORCES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hand_comm
{
template <class ContainerAllocator>
struct hand_GetRawForcesRequest_ {
  typedef hand_GetRawForcesRequest_<ContainerAllocator> Type;

  hand_GetRawForcesRequest_()
  {
  }

  hand_GetRawForcesRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetRawForcesRequest
typedef  ::hand_comm::hand_GetRawForcesRequest_<std::allocator<void> > hand_GetRawForcesRequest;

typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesRequest> hand_GetRawForcesRequestPtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesRequest const> hand_GetRawForcesRequestConstPtr;



template <class ContainerAllocator>
struct hand_GetRawForcesResponse_ {
  typedef hand_GetRawForcesResponse_<ContainerAllocator> Type;

  hand_GetRawForcesResponse_()
  : forces()
  , ret(0)
  , msg()
  {
  }

  hand_GetRawForcesResponse_(const ContainerAllocator& _alloc)
  : forces(_alloc)
  , ret(0)
  , msg(_alloc)
  {
  }

  typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _forces_type;
  std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  forces;

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct hand_GetRawForcesResponse
typedef  ::hand_comm::hand_GetRawForcesResponse_<std::allocator<void> > hand_GetRawForcesResponse;

typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesResponse> hand_GetRawForcesResponsePtr;
typedef boost::shared_ptr< ::hand_comm::hand_GetRawForcesResponse const> hand_GetRawForcesResponseConstPtr;


struct hand_GetRawForces
{

typedef hand_GetRawForcesRequest Request;
typedef hand_GetRawForcesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct hand_GetRawForces
} // namespace hand_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetRawForcesRequest";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fd50740d9347aa4f4ab5b4d7ba228b8e";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfd50740d9347aa4fULL;
  static const uint64_t static_value2 = 0x4ab5b4d7ba228b8eULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetRawForcesResponse";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64[] forces\n\
int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetRawForcesRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.forces);
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hand_GetRawForcesResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hand_comm::hand_GetRawForces> {
  static const char* value() 
  {
    return "fd50740d9347aa4f4ab5b4d7ba228b8e";
  }

  static const char* value(const hand_comm::hand_GetRawForces&) { return value(); } 
};

template<>
struct DataType<hand_comm::hand_GetRawForces> {
  static const char* value() 
  {
    return "hand_comm/hand_GetRawForces";
  }

  static const char* value(const hand_comm::hand_GetRawForces&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fd50740d9347aa4f4ab5b4d7ba228b8e";
  }

  static const char* value(const hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetRawForces";
  }

  static const char* value(const hand_comm::hand_GetRawForcesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fd50740d9347aa4f4ab5b4d7ba228b8e";
  }

  static const char* value(const hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hand_comm/hand_GetRawForces";
  }

  static const char* value(const hand_comm::hand_GetRawForcesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HAND_COMM_SERVICE_HAND_GETRAWFORCES_H

