/* Auto-generated by genmsg_cpp for file /home/mcube/hands_MLab/code/nodes/vision/ROS/vision_comm/srv/GetInfo.srv */
#ifndef VISION_COMM_SERVICE_GETINFO_H
#define VISION_COMM_SERVICE_GETINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "std_msgs/Header.h"



namespace vision_comm
{
template <class ContainerAllocator>
struct GetInfoRequest_ {
  typedef GetInfoRequest_<ContainerAllocator> Type;

  GetInfoRequest_()
  : header()
  , filename()
  {
  }

  GetInfoRequest_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , filename(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  filename;


  typedef boost::shared_ptr< ::vision_comm::GetInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_comm::GetInfoRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetInfoRequest
typedef  ::vision_comm::GetInfoRequest_<std::allocator<void> > GetInfoRequest;

typedef boost::shared_ptr< ::vision_comm::GetInfoRequest> GetInfoRequestPtr;
typedef boost::shared_ptr< ::vision_comm::GetInfoRequest const> GetInfoRequestConstPtr;



template <class ContainerAllocator>
struct GetInfoResponse_ {
  typedef GetInfoResponse_<ContainerAllocator> Type;

  GetInfoResponse_()
  : num_markers(0)
  , certainty()
  , distance(0.0)
  , posx()
  , posy()
  , theta()
  , alpha()
  , r()
  {
    certainty.assign(0.0);
    posx.assign(0.0);
    posy.assign(0.0);
    theta.assign(0.0);
    alpha.assign(0.0);
    r.assign(0.0);
  }

  GetInfoResponse_(const ContainerAllocator& _alloc)
  : num_markers(0)
  , certainty()
  , distance(0.0)
  , posx()
  , posy()
  , theta()
  , alpha()
  , r()
  {
    certainty.assign(0.0);
    posx.assign(0.0);
    posy.assign(0.0);
    theta.assign(0.0);
    alpha.assign(0.0);
    r.assign(0.0);
  }

  typedef int32_t _num_markers_type;
  int32_t num_markers;

  typedef boost::array<double, 4>  _certainty_type;
  boost::array<double, 4>  certainty;

  typedef double _distance_type;
  double distance;

  typedef boost::array<double, 4>  _posx_type;
  boost::array<double, 4>  posx;

  typedef boost::array<double, 4>  _posy_type;
  boost::array<double, 4>  posy;

  typedef boost::array<double, 4>  _theta_type;
  boost::array<double, 4>  theta;

  typedef boost::array<double, 4>  _alpha_type;
  boost::array<double, 4>  alpha;

  typedef boost::array<double, 4>  _r_type;
  boost::array<double, 4>  r;


  typedef boost::shared_ptr< ::vision_comm::GetInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_comm::GetInfoResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetInfoResponse
typedef  ::vision_comm::GetInfoResponse_<std::allocator<void> > GetInfoResponse;

typedef boost::shared_ptr< ::vision_comm::GetInfoResponse> GetInfoResponsePtr;
typedef boost::shared_ptr< ::vision_comm::GetInfoResponse const> GetInfoResponseConstPtr;


struct GetInfo
{

typedef GetInfoRequest Request;
typedef GetInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetInfo
} // namespace vision_comm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vision_comm::GetInfoRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vision_comm::GetInfoRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vision_comm::GetInfoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "37e6a3edab305e40b07540994cd1b883";
  }

  static const char* value(const  ::vision_comm::GetInfoRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x37e6a3edab305e40ULL;
  static const uint64_t static_value2 = 0xb07540994cd1b883ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_comm::GetInfoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_comm/GetInfoRequest";
  }

  static const char* value(const  ::vision_comm::GetInfoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vision_comm::GetInfoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
string filename\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::vision_comm::GetInfoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::vision_comm::GetInfoRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::vision_comm::GetInfoRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vision_comm::GetInfoResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vision_comm::GetInfoResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vision_comm::GetInfoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8aa51de32665edeb41591df7d72c6217";
  }

  static const char* value(const  ::vision_comm::GetInfoResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8aa51de32665edebULL;
  static const uint64_t static_value2 = 0x41591df7d72c6217ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_comm::GetInfoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_comm/GetInfoResponse";
  }

  static const char* value(const  ::vision_comm::GetInfoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vision_comm::GetInfoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 num_markers\n\
float64[4] certainty\n\
float64 distance\n\
float64[4] posx\n\
float64[4] posy\n\
float64[4] theta\n\
float64[4] alpha\n\
float64[4] r\n\
\n\
\n\
";
  }

  static const char* value(const  ::vision_comm::GetInfoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vision_comm::GetInfoResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vision_comm::GetInfoRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.filename);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetInfoRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vision_comm::GetInfoResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.num_markers);
    stream.next(m.certainty);
    stream.next(m.distance);
    stream.next(m.posx);
    stream.next(m.posy);
    stream.next(m.theta);
    stream.next(m.alpha);
    stream.next(m.r);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetInfoResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vision_comm::GetInfo> {
  static const char* value() 
  {
    return "08d6488cfc4c4695e8829ca7f706fcab";
  }

  static const char* value(const vision_comm::GetInfo&) { return value(); } 
};

template<>
struct DataType<vision_comm::GetInfo> {
  static const char* value() 
  {
    return "vision_comm/GetInfo";
  }

  static const char* value(const vision_comm::GetInfo&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vision_comm::GetInfoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "08d6488cfc4c4695e8829ca7f706fcab";
  }

  static const char* value(const vision_comm::GetInfoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vision_comm::GetInfoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_comm/GetInfo";
  }

  static const char* value(const vision_comm::GetInfoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vision_comm::GetInfoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "08d6488cfc4c4695e8829ca7f706fcab";
  }

  static const char* value(const vision_comm::GetInfoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vision_comm::GetInfoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_comm/GetInfo";
  }

  static const char* value(const vision_comm::GetInfoResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VISION_COMM_SERVICE_GETINFO_H

